# fly.toml app configuration file generated for erlang-secure-coding on 2026-03-13T17:31:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'erlang-secure-coding'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '5s'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
